---
checkpoint:
    save_path: checkpoints/audio_wav2vec2/checkpoint.pth
    save_checkpoint: True

solver:
    loss_fn: CE
    balance_classes: False
    num_frozen_epochs: 2
    finetuning:
        warmup_epochs: 2
        lr: 2.0e-6
        weight_decay: 5.0e-5
    frozen:
        lr: 1.0e-4
        weight_decay: 0.01
    epochs: 100
    early_stopping:
        enabled: True
        patience: 3
        restore_best_weights: True

train:
    data_loader:
        shuffle: True
        batch_size: 2
        num_workers: 2
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 2
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 2
        num_workers: 2
        pin_memory: True

wandb:
    enabled: True
    watch_model: False
    project_name: audio_wav2vec2-feature-extractor
    entity: "" # user or team name
    resume_run: False
    resume_run_id: "" # wandb run id to resume

...
