---
checkpoint:
    save_path: checkpoints/text/checkpoint.pth
    save_checkpoint: True

solver:
    loss_fn: CE
    balance_classes: False
    warmup_epochs: 2
    num_frozen_epochs: 2
    frozen_lr: 1.0e-4
    finetuning_lr: 2.0e-6
    weight_decay: 0.01
    epochs: 100
    early_stopping:
        enabled: True
        patience: 5
        restore_best_weights: True

train:
    data_loader:
        shuffle: True
        batch_size: 16
        num_workers: 2
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 16
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 16
        num_workers: 2
        pin_memory: True

wandb:
    enabled: True
    watch_model: False
    project_name: text-feature-extractor

...
