DEBUG:
  enabled: True
  num_samples: 32
  train: True
  visualize: True
  visualization_type: "3D" # 3D or 2D

AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000

checkpoint:
    save_path: checkpoints/audio_feature_extractor.pth
    load_path: checkpoints/audio_feature_extractor.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    adaptive_triplet_margin_loss: False
    covariance_loss: False
    variance_loss: False
    lr: 1.0e-5
    weight_decay: 1.0e-6
    epochs: 50
    scheduler:
        enabled: False
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: False
        patience: 10
        restore_best_weights: True

model:

train:
    data_loader:
        shuffle: True
        batch_size: 2
        num_workers: 3
        pin_memory: True
    max_value: 32.4030  # db scale:32.4030 | normal scale:1738.9810
    min_value: -100

val:
    data_loader:
        shuffle: False
        batch_size: 2
        num_workers: 3
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 3
        pin_memory: True

wandb:
    enabled: False
    watch_model: True
    project_name: audio-mel-embeddings

...
