---

DEBUG:
  enabled: False
  num_samples: 32
  train: True
  visualize: True
  visualization_type: "3D" # 3D or 2D

AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000
    max_duration: 10.0 # seconds
    augmentation_factor : 2 # choose the number of augmentation to do for each image, 1 to disable augmentation

checkpoint:
    save_path: checkpoints/audio_mel/checkpoint.pth
    load_path: checkpoints/audio_mel/checkpoint.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    len_triplet_picking: 100
    adaptive_triplet_margin_loss: True
    covariance_loss: True
    variance_loss: True
    lr: 1.0e-4
    weight_decay: 0.0
    epochs: 50
    scheduler:
        enabled: True
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: True
        patience: 10
        restore_best_weights: True

train:
    data_loader:
        shuffle: True
        batch_size: 32
        num_workers: 2
        pin_memory: True
    # max_value: 32.4030  # db scale:32.4030 | normal scale:1738.9810
    # min_value: -100

val:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

wandb:
    enabled: False
    watch_model: False
    project_name: audio-mel-embeddings

...
