---
AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000

feature_extractors:
    text:
        checkpoint: checkpoints/text/roberta-base # Alternatively, 'roberta-base'
    audio_MEL:
        checkpoint: checkpoints/audio_MEL/resnet18-mel # Alternatively, 'facebook/wav2vec2-base-960h'
    audio_wav2vec:
        checkpoint: checkpoints/audio_wav2vec/wav2vec # Alternatively, 'facebook/wav2vec2-base-960h'

checkpoint:
    save_path: checkpoints/m2fnet.pth
    load_path: checkpoints/m2fnet.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    loss_fn: CE
    balance_classes: False
    lr: 5.0e-4
    weight_decay: 5.0e-5
    epochs: 100
    scheduler:
        enabled: False
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: False
        patience: 10
        restore_best_weights: True

model:
    DROPOUT: 0.4
    AUDIO:
        EMBEDDING_SIZE: 300
        N_HEAD: 8
        N_LAYERS: 1
        N_ENCODERS: 1
    TEXT:
        EMBEDDING_SIZE: 768
        N_HEAD: 8
        N_LAYERS: 1
        N_ENCODERS: 1
    FAM:
        EMBEDDING_SIZE: 768
        N_HEAD: 8
        N_LAYERS: 5
    CLASSIFIER:
        N_LAYERS: 2
        HIDDEN_SIZE: 64
    OUTPUT_SIZE: 7

train:
    data_loader:
        shuffle: True
        batch_size: 4
        num_workers: 0
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 4
        num_workers: 0
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 4
        num_workers: 0
        pin_memory: True

wandb:
    enabled: True
    watch_model: False
    project_name: multimodal-emotion-recognition

...
