---
AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000

embeddings:
    text: embeddings/text_large
    audio: embeddings/audio_wav2vec2

checkpoint:
    save_path: checkpoints/m2fnet.pth
    load_path: checkpoints/m2fnet.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    loss_fn: CE
    balance_classes: False
    lr: 1.0e-4
    weight_decay: 0.01
    epochs: 100
    scheduler:
        enabled: False
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: False
        patience: 5
        restore_best_weights: True

model:
    DROPOUT: 0.4
    AUDIO:
        EMBEDDING_SIZE: 768
        N_HEAD: 8
        N_LAYERS: 6
        N_ENCODERS: 1
    TEXT:
        EMBEDDING_SIZE: 1024
        N_HEAD: 8
        N_LAYERS: 6
        N_ENCODERS: 1
    FAM:
        EMBEDDING_SIZE: 768
        N_HEAD: 8
        N_LAYERS: 5
    CLASSIFIER:
        N_LAYERS: 2
        HIDDEN_SIZE: 128
    OUTPUT_SIZE: 7

train:
    data_loader:
        shuffle: True
        batch_size: 32
        num_workers: 2
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

wandb:
    enabled: True
    watch_model: False
    project_name: multimodal-emotion-recognition

...
