---
AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000

checkpoint:
    save_path: checkpoints/model.pth
    load_path: checkpoints/model.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    loss_fn: CE
    balance_classes: False
    lr: 1.0e-3
    epochs: 1000
    scheduler:
        enabled: False
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: True
        patience: 10
        restore_best_weights: True

model:
    AUDIO:
        EMBEDDING_SIZE: 768
        N_HEAD: 4
        N_LAYERS: 4
    TEXT:
        EMBEDDING_SIZE: 768
        N_HEAD: 4
        N_LAYERS: 4
    FAM:
        EMBEDDING_SIZE: 768
        N_HEAD: 4
        N_LAYERS: 4
    CLASSIFIER:
        N_LAYERS: 2
        HIDDEN_SIZE: 64
    OUTPUT_SIZE: 7

train:
    data_loader:
        shuffle: True
        batch_size: 4
        num_workers: 2
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 4
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 4
        num_workers: 2
        pin_memory: True

wandb:
    enabled: False
    project_name: multimodal-emotion-recognition

...
