---
AUDIO:
    ffmpeg_sr: 16000
    wav2vec_sr: 16000

embeddings:
    text: embeddings/text_base
    audio: embeddings/audio_wav2vec2

checkpoint:
    save_path: checkpoints/m2fnet.pth
    load_path: checkpoints/m2fnet.pth
    save_checkpoint: True
    load_checkpoint: False

solver:
    loss_fn: CE
    balance_classes: False
    lr: 5.0e-5
    weight_decay: 0.01
    epochs: 100
    scheduler:
        enabled: False
        scheduler_fn: ExponentialLR
        gamma: 0.98
    early_stopping:
        enabled: True
        patience: 3
        restore_best_weights: True

model:
    dropout: 0.4
    AUDIO:
        enabled: True
        embedding_size: 768
        n_head: 8
        n_transformers: 1
        n_encoder_layers: 6

    TEXT:
        enabled: True
        embedding_size: 768
        n_head: 8
        n_transformers: 1
        n_encoder_layers: 6
    FAM:
        enabled: True
        embedding_size: 768
        n_head: 8
        n_layers: 5
    CLASSIFIER:
        hidden_size: 768
        output_size: 7
        n_layers: 2

train:
    data_loader:
        shuffle: True
        batch_size: 32
        num_workers: 2
        pin_memory: True

val:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

test:
    data_loader:
        shuffle: False
        batch_size: 32
        num_workers: 2
        pin_memory: True

wandb:
    enabled: False
    watch_model: False
    project_name: multimodal-emotion-recognition

...
